version: '3'
services:
  music-player:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: music-player
    ports:
      - '8857:3000'
    restart: always
    networks:
      - proxy
    labels:
      traefik.enable: true
      traefik.port: 3000
      traefik.http.routers.webhooks.rule: "Host(`musicplayer.tymek.ovh`)"
      traefik.http.services.webhooks.loadbalancer.server.port: 3000
networks:
  proxy:
    name: proxy-network
    external: true